### ISSUE TITLE
Unable to use many VSCode features

### ISSUE THREAD

**Issue by jrbe228** [accetto/headless-coding-g3#1]
Referencing image `accetto/debian-vnc-xfce-vscode-g3:latest`. 
VSCode crashes when attempting to use various features
- Starting a Terminal crashes with error code 4.
- Installing an Extension crashes with error code 133.
- In case the problem was related to user permissions, I switched to root using `sudo su`, then the default `headless` password. When running `code --no-sandbox --user-data-dir /opt` as root user, VSCode opens with a blank screen.

**Comment by accetto** [comment]
Hello @jrbe228,

thank you for your feedback.

I'm using this image myself pretty heavily and it's working well.

I've just tested a fresh download. I've open a terminal window and installed the `Git Graph` extension without problems. All under the default `headless` user (1000:1000). So it seems like the image on the Docker Hub is still all right.

First thing to check: Have you increased the shared memory size (SHM) to at least 256MB?

I also need more information to try to reproduce the issue.

1. On what environment are you?
2. Have you bound any container folders to the folders on your host (using bind mounts)?

Regards,
accetto

**Comment by jrbe228** [comment]
Hi accetto, 
Good to know the latest container is working on some environments. Some runtime settings may be the problem in my case. Some notes and answers to your questions - 

1. My environment is AKS Kubernetes. The compute node is running Containerd 1.7.1 on Ubuntu 22.04. The full image version tag is `AKSUbuntu-2204gen2containerd-202306.01.0`. 
2. In my K8s YAML's resources, I set the min / max CPUs to 0.5 - 4.0. Also I set the min / max memory GB to 0.5 - 16.0. I hope this would sufficiently cover the SHM setting in Docker. 
3. For my testing I did have several K8s persistent volumes mounted to the container. I can try removing these if you suspect it could be causing VSCode instability. 
4. The VSCode extension I eventually need to test is the DevContainer extension.

**Comment by accetto** [comment]
I'm really very sorry, but the current generation was not tested on such environment.

However, I would still check the shared memory size using `df -h /dev/shm` **inside** the container.

What value do you get? Docker sets it to only 64MB by default and taht is not enough. This [wiki page](https://github.com/accetto/xubuntu-vnc/wiki/Firefox-multiprocess#how-to-set-shared-memory-size) in my older project describes how to increase it. Maybe it'll help.

I'm also not sure, if the `DevContainer` extension can work at all **inside** the container. I'm afraid not. Or have I misunderstood you?

**Comment by jrbe228** [comment]
Sure, this is a new environment and I would expect some adjustment to work correctly. I may check the shared memory size next week. 

I'm also unsure if the DevContainer extension can work inside the container. If the extension can install, it would still require Docker-in-Docker to execute DevContainers. 

Lastly, I'm realizing this approach may be more appropriate - https://hub.docker.com/r/linuxserver/code-server. It was designed with Kubernetes as a priority with lots of testing there.

**Comment by accetto** [comment]
Sure, I'm not aiming to compete with such teams. :)

**Comment by jrbe228** [comment]
Good news. Resizing `/dev/shm` to 1.0G fixes the code 4 and code 133 errors with Terminal and Extensions. Note that size does add up quickly as more extensions are installed so I would probably need a larger value in production.

Startup (no extensions or terminal yet):
```
headless@vsc-0:~$ df -h /dev/shm
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           1.0G   15M 1010M   2% /dev/shm
```
After installing all desired extensions: 
```
headless@vsc-0:~$ df -h /dev/shm
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           1.0G  541M  484M  53% /dev/shm
```
This YAML makes it easy to resize in Kubernetes - https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine/46434614#46434614.

**Comment by accetto** [comment]
Thank you for the good news and for the hint. I'm surprised that so much SHM memory is required. With Docker Desktop is 256MB usually enough.
